name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue! I hope to be able to fix your issue as soon as possible.'
        pr-message: 'Awesome! Contributions are always welcome. I will be revieving the pull request shortly.'
